export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-16">

        <div className="mb-10">
          <h1 className="text-3xl font-bold text-textPrimary mb-2">Terms of Service</h1>
          <p className="text-textMuted">Last updated: April 25, 2026</p>
        </div>

        <div className="prose space-y-8">

          <section>
            <h2 className="text-xl font-semibold text-textPrimary mb-3">1. Acceptance of terms</h2>
            <p className="text-textMuted leading-relaxed">
              By creating an account or using FamilyPantry, you agree to these Terms of Service. If you do not agree, please do not use the service. These terms are governed by the laws of British Columbia, Canada.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-textPrimary mb-3">2. Description of service</h2>
            <p className="text-textMuted leading-relaxed">
              FamilyPantry is a grocery management platform that helps families track pantry inventory, generate recipe suggestions using AI, manage grocery lists, monitor food recall alerts, and track grocery spending. The service is provided on a subscription basis with a free tier available.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-textPrimary mb-3">3. Health disclaimer</h2>
            <div className="bg-orange-50 border border-orange-100 rounded-card p-4 mb-3">
              <p className="text-sm font-semibold text-orange-600 mb-1">Important — please read carefully</p>
              <p className="text-sm text-orange-600 leading-relaxed">
                FamilyPantry is NOT a medical service. Recipe suggestions and nutritional information are generated by AI for general wellness purposes only and should not be considered medical advice. Always consult a qualified healthcare professional or registered dietitian for medical dietary needs, especially for managing health conditions such as diabetes, heart disease, allergies, or eating disorders.
              </p>
            </div>
            <p className="text-textMuted leading-relaxed">
              Nutritional information provided is approximate and may not be accurate for all products or preparation methods. FamilyPantry is not responsible for any health outcomes resulting from following recipe suggestions or nutritional guidance provided by the app.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-textPrimary mb-3">4. Food recall alerts</h2>
            <p className="text-textMuted leading-relaxed">
              Food recall information is sourced directly from Health Canada's public database and is provided for informational purposes. While we make every effort to match recalls against your pantry accurately, FamilyPantry cannot guarantee that all recalled products will be identified. Always check Health Canada's official recalls website at recalls-rappels.canada.ca for the most current and complete information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-textPrimary mb-3">5. Subscription and billing</h2>
            <ul className="space-y-2 text-textMuted">
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> Subscriptions are billed monthly and renew automatically</li>
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> You may cancel your subscription at any time from Settings</li>
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> Cancellation takes effect at the end of the current billing period</li>
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> We do not offer refunds for partial months</li>
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> Prices are in Canadian dollars (CAD) unless otherwise stated</li>
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> We reserve the right to change pricing with 30 days notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-textPrimary mb-3">6. Acceptable use</h2>
            <p className="text-textMuted leading-relaxed mb-3">You agree not to:</p>
            <ul className="space-y-2 text-textMuted">
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> Share your account credentials with people outside your family</li>
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> Use the service for any commercial purpose without written permission</li>
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> Attempt to reverse engineer or copy the service</li>
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> Upload false or misleading health information</li>
              <li className="flex gap-2"><span className="text-primary font-bold">·</span> Use the service in any way that violates Canadian law</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-textPrimary mb-3">7. Limitation of liability</h2>
            <p className="text-textMuted leading-relaxed">
              FamilyPantry is provided "as is" without warranties of any kind. To the maximum extent permitted by law, FamilyPantry shall not be liable for any indirect, incidental, or consequential damages arising from use of the service, including but not limited to health outcomes from recipe suggestions, missed food recall alerts, or data loss.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-textPrimary mb-3">8. Account termination</h2>
            <p className="text-textMuted leading-relaxed">
              We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time from Settings. Upon deletion, all your data will be permanently removed within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-textPrimary mb-3">9. Changes to terms</h2>
            <p className="text-textMuted leading-relaxed">
              We may update these terms from time to time. We will notify you of significant changes by email. Continued use of the service after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-textPrimary mb-3">10. Contact</h2>
            <p className="text-textMuted leading-relaxed">
              For questions about these terms, contact us at legal@familypantry.ca
            </p>
          </section>

        </div>
      </div>
    </div>
  )
}